### PR TITLE
Add HTML redirect

### PR DESCRIPTION
**Pull request by tomwilkie**
Signed-off-by: Tom Wilkie <tom@grafana.com>

### CODE REVIEW

**Review by DanCech — APPROVED** [review]

**Comment by DanCech** [comment]
This shouldn't ever be served to new clients since we have a redirect in nginx, but it won't hurt either

**Comment by tomwilkie** [comment]
I'm still getting the old page (maybe stale DNS?)

**Comment by DanCech** [comment]
most likely browser cache, this is what we serve:
```
$ curl -i https://grafana.com/about/events/grafanacon/
HTTP/1.1 302 Moved Temporarily
Server: nginx/1.13.9
Date: Wed, 18 Dec 2019 15:33:15 GMT
Content-Type: text/html
Content-Length: 161
Location: https://grafana.com/about/events/grafanacon/2020/
X-Frame-Options: DENY
Via: 1.1 google
Alt-Svc: clear

<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.13.9</center>
</body>
```

**Comment by tomwilkie** [comment]
I think we're talking cross-purposes.  This redirect is for https://www.grafanacon.org:

```
$ curl https://www.grafanacon.org
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <title>Redirecting to https://grafana.com/about/events/grafanacon/2020/</title>
    <meta http-equiv="refresh" content="0; URL=https://grafana.com/about/events/grafanacon/2020/">
    <link rel="canonical" href="https://grafana.com/about/events/grafanacon/2020/">
</head>
<body>
    <p><a href="https://grafana.com/about/events/grafanacon/2020/">This page has moved to https://grafana.com/about/events/grafanacon/2020/.</a></p>
</body>
</html>
```

Did you change the DNS for this to point to nginx?

**Pull request merged**
